import React from 'react';

export default class MediaButton extends React.Component {
  render() {
    return (
      <div className="flex z-0 absolute left-[-25px] top-[calc(100%-30px)]">
      <div className="hexagon-grid z-0">
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>	
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
      	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<br />
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>
	<div className="hexagon"></div>

      </div>
      </div>
    );
  }
}
